version: '3'

services:
  couchbase-server:
    image: couchbase
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
    environment:
      - COUCHBASE_BUCKET=dataIngestionBucket
      - COUCHBASE_USERNAME=user
      - COUCHBASE_PASSWORD=password
    networks:
      - shared_network

networks:
  shared_network:
    name: shared_network
    driver: bridge
    external: true