version: '3.7'

services:
  jobmanager:
    image: flink:1.12.0 
    ports:
      - "8081:8081"  
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    networks:
      - shared_network

  taskmanager:
    image: flink:1.12.0  
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    networks:
      - shared_network

networks:
  shared_network:
    name: shared_network
    driver: bridge
    external: true
